apiVersion: v1
kind: Service
metadata:
  name: flaskhelloworld
  labels:
    app: flaskhelloworld
    service: flaskhelloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: flaskhelloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskhelloworld
  labels:
    app: flaskhelloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskhelloworld
      version: v1
  template:
    metadata:
      labels:
        app: flaskhelloworld
        version: v1
    spec:
      serviceAccountName: flaskhelloworld
      initContainers:
      - name: flaskhelloworld-init
        image: groundnuty/k8s-wait-for:1.3
        imagePullPolicy: IfNotPresent
        args:
        - "job"
        - "db-app-init"
      containers:
      - name: flaskhelloworld
        envFrom:
          - configMapRef:
              name: db-app-config
          - secretRef:
              name: db-app-secret
        image: sbwise/k8s-db-app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
