apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: k8s-wait-for
    newName: groundnuty/k8s-wait-for
    newTag: "1.3"
  - name: k8s-db-app
    newName: sbwise/k8s-db-app
    newTag: "1.0.1"
  - name: k8s-db-app-init
    newName: sbwise/k8s-db-app-init
    newTag: "1.0.3"

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - job.yaml
  - rbac.yaml
