apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    service: database
spec:
  ports:
  - port: 5432
    name: pg
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-app-secret
                key: PGUSER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-app-secret
                key: PGPASSWORD
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
